# Generated by Django 6.0.4 on 2026-06-16 15:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('maestros', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Saldos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(blank=True, db_column='Codigo', max_length=20, null=True)),
                ('descr', models.CharField(blank=True, db_column='Descr', max_length=200, null=True)),
                ('bodega', models.CharField(blank=True, db_column='Bodega', max_length=10, null=True)),
                ('cantidad', models.FloatField(blank=True, db_column='Cantidad', null=True)),
                ('tipo', models.SmallIntegerField(blank=True, db_column='Tipo', null=True)),
                ('fecha', models.DateTimeField(blank=True, db_column='Fecha', null=True)),
                ('numero', models.FloatField(blank=True, db_column='Numero', null=True)),
            ],
            options={
                'db_table': 'Saldos',
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='Movs',
            fields=[
                ('id', models.AutoField(db_column='id', primary_key=True, serialize=False)),
                ('numero', models.FloatField(db_column='Numero')),
                ('fecha', models.DateTimeField(db_column='Fecha')),
                ('rut', models.CharField(blank=True, db_column='RUT', max_length=13, null=True)),
                ('codencargado', models.FloatField(blank=True, db_column='CodEncargado', null=True)),
                ('tipodocref', models.FloatField(blank=True, db_column='TipoDocRef', null=True)),
                ('docref', models.FloatField(blank=True, db_column='DocRef', null=True)),
                ('bodega', models.FloatField(blank=True, db_column='Bodega', null=True)),
                ('cantidad', models.FloatField(blank=True, db_column='Cantidad', null=True)),
                ('canttotal', models.FloatField(blank=True, db_column='CantTotal', null=True)),
                ('neto', models.FloatField(blank=True, db_column='Neto', null=True)),
                ('iva', models.FloatField(blank=True, db_column='IVA', null=True)),
                ('total', models.FloatField(blank=True, db_column='Total', null=True)),
                ('punit', models.FloatField(blank=True, db_column='PUnit', null=True)),
                ('cup', models.FloatField(blank=True, db_column='CUP', null=True)),
                ('linea', models.FloatField(blank=True, db_column='Linea', null=True)),
                ('proceso', models.FloatField(blank=True, db_column='Proceso', null=True)),
                ('estado', models.CharField(blank=True, db_column='Estado', max_length=10, null=True)),
                ('usr', models.CharField(blank=True, max_length=15, null=True)),
                ('timeuser', models.DateTimeField(blank=True, db_column='TimeUser', null=True)),
                ('pagado', models.BooleanField(blank=True, db_column='Pagado', null=True)),
                ('usar', models.BooleanField(blank=True, db_column='Usar', null=True)),
                ('numid', models.IntegerField(blank=True, null=True)),
                ('fecvence', models.DateTimeField(blank=True, db_column='FecVence', null=True)),
                ('glosa', models.CharField(blank=True, db_column='Glosa', max_length=255, null=True)),
                ('patente_id', models.IntegerField(blank=True, null=True)),
                ('codigo', models.ForeignKey(blank=True, db_column='Codigo', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='maestros.articulos')),
                ('tipo', models.ForeignKey(blank=True, db_column='Tipo', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='maestros.docs')),
            ],
            options={
                'db_table': 'Movs',
                'default_permissions': (),
            },
        ),
    ]
