# Generated by Django 6.0.4 on 2026-06-18 17:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0001_initial'),
        ('maestros', '0003_seed_clasificacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='movs',
            name='categoria',
            field=models.ForeignKey(blank=True, db_column='Categoria', null=True, on_delete=django.db.models.deletion.SET_NULL, to='maestros.clasificacion'),
        ),
        migrations.AddField(
            model_name='movs',
            name='peso',
            field=models.FloatField(blank=True, db_column='Peso', null=True),
        ),
        migrations.AddField(
            model_name='movs',
            name='tratamiento',
            field=models.ForeignKey(blank=True, db_column='Tratamiento', null=True, on_delete=django.db.models.deletion.SET_NULL, to='maestros.tratamientoler'),
        ),
    ]
