# Generated by Django 6.0.4 on 2026-06-18 20:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0002_add_peso_categoria_tratamiento'),
        ('maestros', '0004_add_sucursal'),
    ]

    operations = [
        migrations.AddField(
            model_name='movs',
            name='sucursal',
            field=models.ForeignKey(blank=True, db_column='Sucursal', null=True, on_delete=django.db.models.deletion.SET_NULL, to='maestros.sucursal'),
        ),
    ]
