# Generated by Django 6.0.4 on 2026-05-25 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0002_patente_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Saldos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(blank=True, db_column='Codigo', max_length=20, null=True)),
                ('descr', models.CharField(blank=True, db_column='Descr', max_length=200, null=True)),
                ('bodega', models.CharField(blank=True, db_column='Bodega', max_length=10, null=True)),
                ('cantidad', models.FloatField(blank=True, db_column='Cantidad', null=True)),
                ('tipo', models.SmallIntegerField(blank=True, db_column='Tipo', null=True)),
                ('fecha', models.DateTimeField(blank=True, db_column='Fecha', null=True)),
                ('numero', models.FloatField(blank=True, db_column='Numero', null=True)),
            ],
            options={
                'db_table': 'Saldos',
                'managed': False,
            },
        ),
    ]
