# Generated by Django 6.0.4 on 2026-08-11 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0003_add_sucursal_movs'),
    ]

    operations = [
        migrations.CreateModel(
            name='CertificadoDestinoSustentable',
            fields=[
                ('folio', models.IntegerField(primary_key=True, serialize=False)),
                ('rut', models.CharField(blank=True, max_length=13, null=True)),
                ('nombre', models.CharField(blank=True, max_length=200, null=True)),
                ('fecha_emision', models.DateField(blank=True, null=True)),
                ('fecha_inicio', models.DateField(blank=True, null=True)),
                ('fecha_corte', models.DateField(blank=True, null=True)),
                ('total_kilos', models.FloatField(blank=True, null=True)),
                ('pdf', models.BinaryField(blank=True, null=True)),
                ('usr', models.CharField(blank=True, max_length=15, null=True)),
                ('timeuser', models.DateTimeField(auto_now_add=True, db_column='TimeUser', null=True)),
            ],
            options={
                'db_table': 'CertificadoDestinoSustentable',
                'default_permissions': (),
            },
        ),
    ]
