# Generated by Django 6.0.4 on 2026-08-11 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0004_certificadodestinosustentable'),
    ]

    operations = [
        migrations.AddField(
            model_name='movs',
            name='patente_informada',
            field=models.CharField(blank=True, db_column='PatenteInformada', max_length=50, null=True),
        ),
    ]
