# Generated by Django 6.0.4 on 2026-06-16 15:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('maestros', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroArticuloCabecera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_hora', models.DateTimeField(auto_now_add=True)),
                ('documento', models.TextField(blank=True, default='')),
                ('estado', models.CharField(choices=[('INGRESADO', 'Ingresado'), ('PENDIENTE', 'Pendiente'), ('CERRADO', 'Cerrado')], default='INGRESADO', max_length=20)),
                ('folio', models.IntegerField(blank=True, db_index=True, null=True, verbose_name='Folio')),
                ('tipo_registro', models.CharField(choices=[('PE', 'Parte de Entrada'), ('VC', 'Vale de Consumo')], default='PE', max_length=2)),
                ('ot_numero', models.FloatField(blank=True, null=True, verbose_name='Número de OT')),
                ('codencargado', models.FloatField(blank=True, null=True, verbose_name='Código Encargado')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='registros_cabecera', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'RegistroArticuloCabecera',
                'ordering': ['-fecha_hora'],
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='RegistroArticuloDetalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.FloatField()),
                ('observacion', models.TextField(blank=True, default='')),
                ('articulo', models.ForeignKey(db_column='ArticuloCodigo', on_delete=django.db.models.deletion.PROTECT, related_name='registros_detalle', to='maestros.articulos')),
                ('cabecera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='registros.registroarticulocabecera')),
            ],
            options={
                'db_table': 'RegistroArticuloDetalle',
                'default_permissions': (),
            },
        ),
    ]
