# Generated by Django 6.0.4 on 2026-05-25 19:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('maestros', '0009_populate_tipoarticulo_fk'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroArticuloCabecera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_hora', models.DateTimeField(auto_now_add=True)),
                ('documento', models.TextField(blank=True, default='')),
                ('estado', models.CharField(choices=[('INGRESADO', 'Ingresado'), ('PENDIENTE', 'Pendiente'), ('CERRADO', 'Cerrado')], default='INGRESADO', max_length=20)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='registros_cabecera', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Registro de Artículo',
                'verbose_name_plural': 'Registros de Artículos',
                'db_table': 'RegistroArticuloCabecera',
                'ordering': ['-fecha_hora'],
            },
        ),
        migrations.CreateModel(
            name='RegistroArticuloDetalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.FloatField()),
                ('observacion', models.TextField(blank=True, default='')),
                ('articulo', models.ForeignKey(db_column='ArticuloCodigo', on_delete=django.db.models.deletion.PROTECT, related_name='registros_detalle', to='maestros.articulos')),
                ('cabecera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='registros.registroarticulocabecera')),
            ],
            options={
                'verbose_name': 'Detalle de Registro',
                'verbose_name_plural': 'Detalles de Registros',
                'db_table': 'RegistroArticuloDetalle',
            },
        ),
    ]
