# Generated by Django 6.0.4 on 2026-05-26 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registros', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='registroarticulocabecera',
            name='folio',
            field=models.IntegerField(blank=True, db_index=True, null=True, verbose_name='Folio'),
        ),
    ]
