# Generated by Django 6.0.4 on 2026-06-01 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registros', '0002_registroarticulocabecera_folio'),
    ]

    operations = [
        migrations.AddField(
            model_name='registroarticulocabecera',
            name='codencargado',
            field=models.FloatField(blank=True, null=True, verbose_name='Código Encargado'),
        ),
        migrations.AddField(
            model_name='registroarticulocabecera',
            name='ot_numero',
            field=models.FloatField(blank=True, null=True, verbose_name='Número de OT'),
        ),
        migrations.AddField(
            model_name='registroarticulocabecera',
            name='tipo_registro',
            field=models.CharField(choices=[('PE', 'Parte de Entrada'), ('VC', 'Vale de Consumo')], default='PE', max_length=2),
        ),
    ]
