# Generated by Django 6.0.4 on 2026-05-01 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('id', models.CharField(db_collation='Modern_Spanish_CI_AS', db_column='ID', max_length=15, primary_key=True, serialize=False)),
                ('nombres', models.CharField(blank=True, db_collation='Modern_Spanish_CI_AS', db_column='Nombres', max_length=30, null=True)),
                ('pass_field', models.CharField(db_collation='Modern_Spanish_CI_AS', db_column='Pass', max_length=15)),
                ('perfil', models.SmallIntegerField(db_column='Perfil')),
            ],
            options={
                'db_table': 'Usuarios',
                'managed': False,
            },
        ),
    ]
