# Generated by Django 6.0.4 on 2026-05-05 19:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_usuarios'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AppConfig',
        ),
    ]
