# Generated by Django 6.0.4 on 2026-05-01 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Articulos',
            fields=[
                ('codigo', models.CharField(db_collation='Modern_Spanish_CI_AS', db_column='Codigo', max_length=20, primary_key=True, serialize=False)),
                ('descr', models.CharField(db_collation='Modern_Spanish_CI_AS', db_column='Descr', max_length=255)),
                ('um', models.CharField(db_collation='Modern_Spanish_CI_AS', db_column='UM', max_length=255)),
                ('tipo', models.CharField(db_collation='Modern_Spanish_CI_AS', db_column='Tipo', max_length=255)),
                ('precio', models.IntegerField(blank=True, db_column='Precio', null=True)),
                ('cup', models.FloatField(blank=True, db_column='CUP', null=True)),
                ('feculen', models.CharField(blank=True, db_collation='Modern_Spanish_CI_AS', db_column='FECULEN', max_length=255, null=True)),
                ('feculsa', models.CharField(blank=True, db_collation='Modern_Spanish_CI_AS', db_column='FECULSA', max_length=255, null=True)),
                ('mermac', models.CharField(blank=True, db_collation='Modern_Spanish_CI_AS', db_column='MERMAC', max_length=255, null=True)),
                ('stock', models.CharField(blank=True, db_collation='Modern_Spanish_CI_AS', db_column='Stock', max_length=255, null=True)),
                ('stomin', models.FloatField(blank=True, db_column='STOMIN', null=True)),
                ('stomax', models.FloatField(blank=True, db_column='STOMAX', null=True)),
                ('proced', models.CharField(blank=True, db_collation='Modern_Spanish_CI_AS', db_column='PROCED', max_length=255, null=True)),
                ('bodega', models.CharField(blank=True, db_collation='Modern_Spanish_CI_AS', db_column='Bodega', max_length=255, null=True)),
                ('cupx', models.CharField(blank=True, db_collation='Modern_Spanish_CI_AS', db_column='CUPX', max_length=255, null=True)),
                ('cumax', models.CharField(blank=True, db_collation='Modern_Spanish_CI_AS', db_column='CUMAX', max_length=255, null=True)),
                ('imagen', models.CharField(blank=True, db_collation='Modern_Spanish_CI_AS', db_column='Imagen', max_length=255, null=True)),
                ('prc', models.FloatField(db_column='Prc')),
                ('usr', models.CharField(blank=True, db_collation='Modern_Spanish_CI_AS', max_length=15, null=True)),
                ('timeuser', models.DateTimeField(blank=True, db_column='TimeUser', null=True)),
            ],
            options={
                'db_table': 'Articulos',
                'managed': False,
            },
        ),
    ]
