# Generated by Django 6.0.4 on 2026-06-16 15:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bodegas',
            fields=[
                ('cod', models.SmallIntegerField(db_column='Cod', primary_key=True, serialize=False)),
                ('nombre', models.CharField(db_column='Nombre', max_length=50)),
                ('glosa', models.CharField(blank=True, db_column='Glosa', max_length=50, null=True)),
                ('estado', models.CharField(default='Activo', max_length=20)),
                ('usr', models.CharField(blank=True, max_length=15, null=True)),
                ('timeuser', models.DateTimeField(blank=True, db_column='TimeUser', null=True)),
            ],
            options={
                'db_table': 'Bodegas',
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='Cpago',
            fields=[
                ('cod', models.SmallIntegerField(db_column='Cod', primary_key=True, serialize=False)),
                ('descr', models.CharField(blank=True, db_column='Descr', max_length=50, null=True)),
                ('glosa', models.CharField(blank=True, db_column='Glosa', max_length=50, null=True)),
                ('dias', models.SmallIntegerField(blank=True, db_column='Dias', null=True)),
                ('estado', models.CharField(default='Activo', max_length=20)),
            ],
            options={
                'db_table': 'CPago',
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='Docs',
            fields=[
                ('cod', models.SmallIntegerField(db_column='Cod', primary_key=True, serialize=False)),
                ('nombre', models.CharField(db_column='Nombre', max_length=50)),
                ('signo', models.SmallIntegerField(blank=True, db_column='Signo', null=True)),
                ('estado', models.CharField(default='Activo', max_length=20)),
                ('usr', models.CharField(blank=True, max_length=15, null=True)),
                ('timeuser', models.DateTimeField(blank=True, db_column='TimeUser', null=True)),
            ],
            options={
                'db_table': 'Docs',
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='Procesos',
            fields=[
                ('cod', models.SmallIntegerField(db_column='Cod', primary_key=True, serialize=False)),
                ('nombre', models.CharField(db_column='Nombre', max_length=50)),
                ('glosa', models.CharField(blank=True, db_column='Glosa', max_length=50, null=True)),
                ('estado', models.CharField(default='Activo', max_length=20)),
                ('usr', models.CharField(blank=True, max_length=15, null=True)),
                ('timeuser', models.DateTimeField(blank=True, db_column='TimeUser', null=True)),
            ],
            options={
                'db_table': 'Procesos',
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='Provclientes',
            fields=[
                ('rut', models.CharField(db_column='RUT', max_length=13, primary_key=True, serialize=False)),
                ('dig_ver', models.CharField(blank=True, db_column='DIG_VER', max_length=1, null=True)),
                ('nombre', models.CharField(db_column='NOMBRE', max_length=50)),
                ('sigla', models.CharField(blank=True, db_column='SIGLA', max_length=20, null=True)),
                ('giro', models.CharField(blank=True, db_column='GIRO', max_length=50, null=True)),
                ('tipo', models.CharField(db_column='Tipo', max_length=12)),
                ('cpago', models.SmallIntegerField(blank=True, db_column='CPago', null=True)),
                ('direccion', models.CharField(blank=True, db_column='Direccion', max_length=50, null=True)),
                ('comuna', models.CharField(blank=True, db_column='COMUNA', max_length=18, null=True)),
                ('ciudad', models.CharField(blank=True, db_column='CIUDAD', max_length=20, null=True)),
                ('fono', models.CharField(blank=True, db_column='FONO', max_length=20, null=True)),
                ('fax', models.CharField(blank=True, db_column='FAX', max_length=20, null=True)),
                ('email', models.CharField(blank=True, max_length=50, null=True)),
                ('contacto', models.CharField(blank=True, db_column='Contacto', max_length=50, null=True)),
                ('emailcontacto', models.CharField(blank=True, db_column='emailContacto', max_length=50, null=True)),
                ('zona', models.DecimalField(blank=True, db_column='ZONA', decimal_places=0, max_digits=4, null=True)),
                ('vend', models.DecimalField(blank=True, db_column='VEND', decimal_places=0, max_digits=4, null=True)),
                ('cred_max', models.DecimalField(blank=True, db_column='CRED_MAX', decimal_places=2, max_digits=14, null=True)),
                ('vig_cred', models.DateTimeField(blank=True, db_column='VIG_CRED', null=True)),
                ('lis_pre', models.DecimalField(blank=True, db_column='LIS_PRE', decimal_places=0, max_digits=4, null=True)),
                ('vta_acu', models.DecimalField(blank=True, db_column='VTA_ACU', decimal_places=2, max_digits=14, null=True)),
                ('vta_mes', models.DecimalField(blank=True, db_column='VTA_MES', decimal_places=2, max_digits=12, null=True)),
                ('over1', models.CharField(blank=True, db_column='OVER1', max_length=10, null=True)),
                ('ult_com', models.DateTimeField(blank=True, db_column='ULT_COM', null=True)),
                ('rut_fac', models.CharField(blank=True, db_column='RUT_FAC', max_length=20, null=True)),
                ('por_deuda', models.DecimalField(blank=True, db_column='POR_DEUDA', decimal_places=2, max_digits=6, null=True)),
                ('retraso', models.DecimalField(blank=True, db_column='RETRASO', decimal_places=0, max_digits=4, null=True)),
                ('tipo_iva', models.DecimalField(blank=True, db_column='TIPO_IVA', decimal_places=0, max_digits=4, null=True)),
                ('usr', models.CharField(blank=True, max_length=15, null=True)),
                ('timeuser', models.DateTimeField(blank=True, db_column='TimeUser', null=True)),
            ],
            options={
                'db_table': 'ProvClientes',
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='TipoArticulo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True)),
                ('descripcion', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'Tipo de Artículo',
                'verbose_name_plural': 'Tipos de Artículos',
                'db_table': 'TipoArticulo',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Transportistas',
            fields=[
                ('rut', models.CharField(max_length=13, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('estado', models.CharField(default='Activo', max_length=20)),
                ('usr', models.CharField(blank=True, max_length=15, null=True)),
                ('timeuser', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'Transportistas',
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='UnidadMedida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30, unique=True)),
                ('abreviatura', models.CharField(max_length=10)),
            ],
            options={
                'verbose_name': 'Unidad de Medida',
                'verbose_name_plural': 'Unidades de Medida',
                'db_table': 'UnidadMedida',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Empleados',
            fields=[
                ('cod', models.SmallIntegerField(db_column='Cod', primary_key=True, serialize=False)),
                ('nombre', models.CharField(db_column='Nombre', max_length=50)),
                ('glosa', models.CharField(blank=True, db_column='Glosa', max_length=50, null=True)),
                ('estado', models.CharField(default='Activo', max_length=20)),
                ('usr', models.CharField(blank=True, max_length=15, null=True)),
                ('timeuser', models.DateTimeField(blank=True, db_column='TimeUser', null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='empleado', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'Empleados',
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='Articulos',
            fields=[
                ('codigo', models.CharField(db_column='Codigo', max_length=20, primary_key=True, serialize=False)),
                ('descr', models.CharField(db_column='Descr', max_length=255)),
                ('um', models.CharField(db_column='UM', max_length=255)),
                ('tipo', models.CharField(db_column='Tipo', max_length=255)),
                ('precio', models.IntegerField(blank=True, db_column='Precio', null=True)),
                ('cup', models.FloatField(blank=True, db_column='CUP', null=True)),
                ('feculen', models.CharField(blank=True, db_column='FECULEN', max_length=255, null=True)),
                ('feculsa', models.CharField(blank=True, db_column='FECULSA', max_length=255, null=True)),
                ('mermac', models.CharField(blank=True, db_column='MERMAC', max_length=255, null=True)),
                ('stock', models.CharField(blank=True, db_column='Stock', max_length=255, null=True)),
                ('stomin', models.FloatField(blank=True, db_column='STOMIN', null=True)),
                ('stomax', models.FloatField(blank=True, db_column='STOMAX', null=True)),
                ('proced', models.CharField(blank=True, db_column='PROCED', max_length=255, null=True)),
                ('bodega', models.CharField(blank=True, db_column='Bodega', max_length=255, null=True)),
                ('cupx', models.CharField(blank=True, db_column='CUPX', max_length=255, null=True)),
                ('cumax', models.CharField(blank=True, db_column='CUMAX', max_length=255, null=True)),
                ('imagen', models.CharField(blank=True, db_column='Imagen', max_length=255, null=True)),
                ('prc', models.FloatField(db_column='Prc')),
                ('usr', models.CharField(blank=True, max_length=15, null=True)),
                ('timeuser', models.DateTimeField(blank=True, db_column='TimeUser', null=True)),
                ('tipo_articulo', models.ForeignKey(blank=True, db_column='TipoArticuloId', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='articulos', to='maestros.tipoarticulo')),
            ],
            options={
                'db_table': 'Articulos',
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='Patentes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patente', models.CharField(max_length=10, unique=True)),
                ('transportista', models.ForeignKey(db_column='rut_transportista', on_delete=django.db.models.deletion.CASCADE, related_name='patentes', to='maestros.transportistas')),
            ],
            options={
                'db_table': 'Patentes',
                'default_permissions': (),
            },
        ),
    ]
