# Generated by Django 6.0.4 on 2026-06-18 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maestros', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Clasificacion',
            fields=[
                ('codigo', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Clasificación',
                'verbose_name_plural': 'Clasificaciones',
                'db_table': 'Clasificacion',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='TratamientoLER',
            fields=[
                ('codigo_ler', models.CharField(db_column='CodigoLER', max_length=20, primary_key=True, serialize=False)),
                ('descripcion', models.CharField(db_column='Descripcion', max_length=255)),
                ('codigo_ara', models.CharField(db_column='CodigoARA', max_length=20)),
            ],
            options={
                'verbose_name': 'Tratamiento LER',
                'verbose_name_plural': 'Tratamientos LER',
                'db_table': 'TratamientoLER',
                'managed': True,
            },
        ),
    ]
