# Generated by Django 6.0.4 on 2026-05-01 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maestros', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Procesos',
            fields=[
                ('cod', models.SmallIntegerField(db_column='Cod', primary_key=True, serialize=False)),
                ('nombre', models.CharField(db_collation='Modern_Spanish_CI_AS', db_column='Nombre', max_length=50)),
                ('glosa', models.CharField(blank=True, db_collation='Modern_Spanish_CI_AS', db_column='Glosa', max_length=50, null=True)),
                ('usr', models.CharField(blank=True, db_collation='Modern_Spanish_CI_AS', max_length=15, null=True)),
                ('timeuser', models.DateTimeField(blank=True, db_column='TimeUser', null=True)),
            ],
            options={
                'db_table': 'Procesos',
                'managed': False,
            },
        ),
    ]
