# Generated by Django 6.0.4 on 2026-06-18 15:04

from django.db import migrations


def seed_clasificaciones(apps, schema_editor):
    Clasificacion = apps.get_model('maestros', 'Clasificacion')
    data = [
        ("01", "DESPUNTE DE MADERA"),
        ("02", "ESTRUCTURA DE MADERA"),
        ("03", "PALLETS"),
        ("04", "ASERRIN"),
        ("05", "VIRUTA"),
        ("06", "ASTILLAS"),
    ]
    for codigo, descripcion in data:
        Clasificacion.objects.get_or_create(codigo=codigo, descripcion=descripcion)


class Migration(migrations.Migration):

    dependencies = [
        ('maestros', '0002_clasificacion_tratamiento_ler'),
    ]

    operations = [
        migrations.RunPython(seed_clasificaciones),
    ]
