# Generated by Django 6.0.4 on 2026-06-18 20:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maestros', '0003_seed_clasificacion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sucursal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(db_column='Codigo', max_length=20)),
                ('nombre', models.CharField(db_column='Nombre', max_length=100)),
                ('direccion', models.CharField(blank=True, db_column='Direccion', max_length=100, null=True)),
                ('comuna', models.CharField(blank=True, db_column='Comuna', max_length=50, null=True)),
                ('ciudad', models.CharField(blank=True, db_column='Ciudad', max_length=50, null=True)),
                ('fono', models.CharField(blank=True, db_column='Fono', max_length=20, null=True)),
                ('contacto', models.CharField(blank=True, db_column='Contacto', max_length=100, null=True)),
                ('estado', models.CharField(db_column='Estado', default='Activo', max_length=20)),
                ('cliente', models.ForeignKey(db_column='RutCliente', on_delete=django.db.models.deletion.CASCADE, related_name='sucursales', to='maestros.provclientes')),
            ],
            options={
                'verbose_name': 'Sucursal',
                'verbose_name_plural': 'Sucursales',
                'db_table': 'Sucursales',
                'managed': True,
                'unique_together': {('cliente', 'codigo')},
            },
        ),
    ]
