# Generated by Django 6.0.4 on 2026-05-01 20:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maestros', '0003_tipoarticulo_unidadmedida'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tipoarticulo',
            options={'managed': True, 'verbose_name': 'Tipo de Artículo', 'verbose_name_plural': 'Tipos de Artículos'},
        ),
        migrations.AlterModelOptions(
            name='unidadmedida',
            options={'managed': True, 'verbose_name': 'Unidad de Medida', 'verbose_name_plural': 'Unidades de Medida'},
        ),
    ]
