# Generated by Django 6.0.4 on 2026-05-05 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maestros', '0004_alter_tipoarticulo_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bodegas',
            fields=[
                ('cod', models.SmallIntegerField(db_column='Cod', primary_key=True, serialize=False)),
                ('nombre', models.CharField(db_collation='Modern_Spanish_CI_AS', db_column='Nombre', max_length=50)),
                ('glosa', models.CharField(blank=True, db_collation='Modern_Spanish_CI_AS', db_column='Glosa', max_length=50, null=True)),
                ('usr', models.CharField(blank=True, db_collation='Modern_Spanish_CI_AS', max_length=15, null=True)),
                ('timeuser', models.DateTimeField(blank=True, db_column='TimeUser', null=True)),
            ],
            options={
                'db_table': 'Bodegas',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Cpago',
            fields=[
                ('cod', models.SmallIntegerField(db_column='Cod', primary_key=True, serialize=False)),
                ('descr', models.CharField(blank=True, db_collation='Modern_Spanish_CI_AS', db_column='Descr', max_length=50, null=True)),
                ('glosa', models.CharField(blank=True, db_collation='Modern_Spanish_CI_AS', db_column='Glosa', max_length=50, null=True)),
                ('dias', models.SmallIntegerField(blank=True, db_column='Dias', null=True)),
            ],
            options={
                'db_table': 'CPago',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Docs',
            fields=[
                ('cod', models.SmallIntegerField(db_column='Cod', primary_key=True, serialize=False)),
                ('nombre', models.CharField(db_collation='Modern_Spanish_CI_AS', db_column='Nombre', max_length=50)),
                ('signo', models.SmallIntegerField(blank=True, db_column='Signo', null=True)),
                ('usr', models.CharField(blank=True, db_collation='Modern_Spanish_CI_AS', max_length=15, null=True)),
                ('timeuser', models.DateTimeField(blank=True, db_column='TimeUser', null=True)),
            ],
            options={
                'db_table': 'Docs',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Empleados',
            fields=[
                ('cod', models.SmallIntegerField(db_column='Cod', primary_key=True, serialize=False)),
                ('nombre', models.CharField(db_collation='Modern_Spanish_CI_AS', db_column='Nombre', max_length=50)),
                ('glosa', models.CharField(blank=True, db_collation='Modern_Spanish_CI_AS', db_column='Glosa', max_length=50, null=True)),
                ('usr', models.CharField(blank=True, db_collation='Modern_Spanish_CI_AS', max_length=15, null=True)),
                ('timeuser', models.DateTimeField(blank=True, db_column='TimeUser', null=True)),
            ],
            options={
                'db_table': 'Empleados',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Provclientes',
            fields=[
                ('rut', models.CharField(db_collation='Modern_Spanish_CI_AS', db_column='RUT', max_length=13, primary_key=True, serialize=False)),
                ('dig_ver', models.CharField(blank=True, db_collation='Modern_Spanish_CI_AS', db_column='DIG_VER', max_length=1, null=True)),
                ('nombre', models.CharField(db_collation='Modern_Spanish_CI_AS', db_column='NOMBRE', max_length=50)),
                ('sigla', models.CharField(blank=True, db_collation='Modern_Spanish_CI_AS', db_column='SIGLA', max_length=20, null=True)),
                ('giro', models.CharField(blank=True, db_collation='Modern_Spanish_CI_AS', db_column='GIRO', max_length=50, null=True)),
                ('tipo', models.CharField(db_collation='Modern_Spanish_CI_AS', db_column='Tipo', max_length=12)),
                ('cpago', models.SmallIntegerField(blank=True, db_column='CPago', null=True)),
                ('direccion', models.CharField(blank=True, db_collation='Modern_Spanish_CI_AS', db_column='Direccion', max_length=50, null=True)),
                ('comuna', models.CharField(blank=True, db_collation='Modern_Spanish_CI_AS', db_column='COMUNA', max_length=18, null=True)),
                ('ciudad', models.CharField(blank=True, db_collation='Modern_Spanish_CI_AS', db_column='CIUDAD', max_length=20, null=True)),
                ('fono', models.CharField(blank=True, db_collation='Modern_Spanish_CI_AS', db_column='FONO', max_length=20, null=True)),
                ('fax', models.CharField(blank=True, db_collation='Modern_Spanish_CI_AS', db_column='FAX', max_length=20, null=True)),
                ('email', models.CharField(blank=True, db_collation='Modern_Spanish_CI_AS', max_length=50, null=True)),
                ('contacto', models.CharField(blank=True, db_collation='Modern_Spanish_CI_AS', db_column='Contacto', max_length=50, null=True)),
                ('emailcontacto', models.CharField(blank=True, db_collation='Modern_Spanish_CI_AS', db_column='emailContacto', max_length=50, null=True)),
                ('zona', models.DecimalField(blank=True, db_column='ZONA', decimal_places=0, max_digits=4, null=True)),
                ('vend', models.DecimalField(blank=True, db_column='VEND', decimal_places=0, max_digits=4, null=True)),
                ('cred_max', models.DecimalField(blank=True, db_column='CRED_MAX', decimal_places=2, max_digits=14, null=True)),
                ('vig_cred', models.DateTimeField(blank=True, db_column='VIG_CRED', null=True)),
                ('lis_pre', models.DecimalField(blank=True, db_column='LIS_PRE', decimal_places=0, max_digits=4, null=True)),
                ('vta_acu', models.DecimalField(blank=True, db_column='VTA_ACU', decimal_places=2, max_digits=14, null=True)),
                ('vta_mes', models.DecimalField(blank=True, db_column='VTA_MES', decimal_places=2, max_digits=12, null=True)),
                ('over1', models.CharField(blank=True, db_collation='Modern_Spanish_CI_AS', db_column='OVER1', max_length=10, null=True)),
                ('ult_com', models.DateTimeField(blank=True, db_column='ULT_COM', null=True)),
                ('rut_fac', models.CharField(blank=True, db_collation='Modern_Spanish_CI_AS', db_column='RUT_FAC', max_length=20, null=True)),
                ('por_deuda', models.DecimalField(blank=True, db_column='POR_DEUDA', decimal_places=2, max_digits=6, null=True)),
                ('retraso', models.DecimalField(blank=True, db_column='RETRASO', decimal_places=0, max_digits=4, null=True)),
                ('tipo_iva', models.DecimalField(blank=True, db_column='TIPO_IVA', decimal_places=0, max_digits=4, null=True)),
                ('usr', models.CharField(blank=True, db_collation='Modern_Spanish_CI_AS', max_length=15, null=True)),
                ('timeuser', models.DateTimeField(blank=True, db_column='TimeUser', null=True)),
            ],
            options={
                'db_table': 'ProvClientes',
                'managed': False,
            },
        ),
    ]
