# Generated by Django 6.0.4 on 2026-08-06 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maestros', '0005_articulos_categoria_tratamiento'),
    ]

    operations = [
        migrations.AddField(
            model_name='clasificacion',
            name='estado',
            field=models.CharField(db_column='Estado', default='Activo', max_length=20),
        ),
        migrations.AddField(
            model_name='tratamientoler',
            name='estado',
            field=models.CharField(db_column='Estado', default='Activo', max_length=20),
        ),
    ]
