# Generated by Django 6.0.4 on 2026-05-08 22:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maestros', '0005_bodegas_cpago_docs_empleados_provclientes'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transportistas',
            fields=[
                ('rut', models.CharField(max_length=13, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Transportista',
                'verbose_name_plural': 'Transportistas',
                'db_table': 'Transportistas',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Patentes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patente', models.CharField(max_length=10, unique=True)),
                ('transportista', models.ForeignKey(db_column='rut_transportista', on_delete=django.db.models.deletion.CASCADE, related_name='patentes', to='maestros.transportistas')),
            ],
            options={
                'verbose_name': 'Patente',
                'verbose_name_plural': 'Patentes',
                'db_table': 'Patentes',
                'managed': True,
            },
        ),
    ]
