# Generated by Django 6.0.4 on 2026-05-11 19:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maestros', '0006_transportistas'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='articulos',
            options={'managed': True},
        ),
    ]
