# Generated by Django 6.0.4 on 2026-08-19 17:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maestros', '0006_clasificacion_tratamiento_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patentes',
            name='patente',
            field=models.CharField(max_length=15, unique=True),
        ),
        migrations.AlterField(
            model_name='patentes',
            name='transportista',
            field=models.ForeignKey(blank=True, db_column='rut_transportista', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='patentes', to='maestros.transportistas'),
        ),
    ]
