# Generated by Django 6.0.4 on 2026-05-11 19:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maestros', '0007_alter_articulos_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='articulos',
            name='tipo_articulo',
            field=models.ForeignKey(blank=True, db_column='TipoArticuloId', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='articulos', to='maestros.tipoarticulo'),
        ),
    ]
