# Generated by Django 6.0.4 on 2026-05-11 19:23

from django.db import migrations


def populate_tipoarticulo_fk(apps, schema_editor):
    Articulos = apps.get_model('maestros', 'Articulos')
    TipoArticulo = apps.get_model('maestros', 'TipoArticulo')

    tipo_map = {t.nombre: t for t in TipoArticulo.objects.all()}

    for art in Articulos.objects.filter(tipo_articulo__isnull=True).exclude(tipo__exact='').exclude(tipo__isnull=True).iterator():
        ta = tipo_map.get(art.tipo)
        if ta:
            Articulos.objects.filter(pk=art.pk).update(tipo_articulo=ta)


class Migration(migrations.Migration):

    dependencies = [
        ('maestros', '0008_add_tipoarticulo_fk'),
    ]

    operations = [
        migrations.RunPython(populate_tipoarticulo_fk, migrations.RunPython.noop),
    ]
