# Generated by Django 6.0.4 on 2026-05-29 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maestros', '0009_populate_tipoarticulo_fk'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bodegas',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='cpago',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='docs',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='empleados',
            options={'managed': True},
        ),
        migrations.AddField(
            model_name='transportistas',
            name='estado',
            field=models.CharField(default='Activo', max_length=20),
        ),
        migrations.AddField(
            model_name='transportistas',
            name='timeuser',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transportistas',
            name='usr',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
