# Generated by Django 6.0.4 on 2026-05-29 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maestros', '0010_add_estado_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='bodegas',
            name='estado',
            field=models.CharField(default='Activo', max_length=20),
        ),
        migrations.AddField(
            model_name='cpago',
            name='estado',
            field=models.CharField(default='Activo', max_length=20),
        ),
        migrations.AddField(
            model_name='docs',
            name='estado',
            field=models.CharField(default='Activo', max_length=20),
        ),
        migrations.AddField(
            model_name='empleados',
            name='estado',
            field=models.CharField(default='Activo', max_length=20),
        ),
    ]
