# Generated by Django 6.0.4 on 2026-05-29 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maestros', '0011_add_estado_to_params'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='procesos',
            options={'managed': True},
        ),
    ]
