# Generated by Django 6.0.4 on 2026-05-29 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maestros', '0012_add_estado_to_procesos'),
    ]

    operations = [
        migrations.RunSQL(
            sql="ALTER TABLE [Procesos] ADD [estado] nvarchar(20) DEFAULT 'Activo' NOT NULL;",
            reverse_sql="ALTER TABLE [Procesos] DROP COLUMN [estado];"
        ),
    ]
