# Generated by Django 6.0.4 on 2026-05-29 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maestros', '0013_add_estado_to_procesos_v2'),
    ]

    operations = [
        migrations.AddField(
            model_name='procesos',
            name='estado',
            field=models.CharField(default='Activo', max_length=20),
        ),
    ]
